const { API_URL } = process.env;

const apiUrls = {
    root: `${API_URL}/api`,
    login: `${API_URL}/login`,
    logout: `${API_URL}/logout`,
    microsoftLogin: `${API_URL}/microsoft/login`,
    designation: `${API_URL}/api/designation`,
    employee: `${API_URL}/api/employees`,
    employeeList: `${API_URL}/api/employees`,
    domainList: `${API_URL}/api/organisation/domains`,
    settingList: `${API_URL}/api/organisation/general-settings`,
    reporteeList: `${API_URL}/api/employees/by-manager`,
    managersList: `${API_URL}/api/employees/managers`,
    experienceList: `${API_URL}/api/employees/experience-list`,
    genderList: `${API_URL}/api/employees/gender-list`,
    mutateEmployeeList: `${API_URL}/api/employees`,
    onboardingFlow: `${API_URL}/api/employees/onboarding-flow`,
    singleEmployee: `${API_URL}/api/employees/by-id`,
    feedback: `${API_URL}/api/feedback`,
    feedbackRequest: `${API_URL}/api/feedback-request`,
    singleRequestedFeedback: `${API_URL}/api/feedback-request`, // pass : /{feedback-request-id}
    markFeedbackReceievedAsRead: `${API_URL}/api/feedback`, // pass: /{id}/mark-read
    markRead: `/mark-read`,
    role: `${API_URL}/api/role`,
    teams: `${API_URL}/api/teams`,
    departments: `${API_URL}/api/departments`,
    kpi: `${API_URL}/api/kpi`,
    kra: `${API_URL}/api/kra`,
    performanceReviewCycles: `${API_URL}/api/review-cycle`,
    tags: `${API_URL}/api/feedback-type`,
    permissionModules: `${API_URL}/api/module`,
    review: `${API_URL}/api/self-review`,
    dashboardChart: `${API_URL}/api/dashboard`,
    feedbackOverview: `${API_URL}/api/dashboard/feedback-overview`,
    dashboardAppreciation: `${API_URL}/api/dashboard/employee-feedback`,
    dashboardFeedbackPercentage: `${API_URL}/api/dashboard/feedback-percentage`,
    dashboardActionItems: `${API_URL}/api/dashboard/action-item`,
    reviewTimeline: `${API_URL}/api/review-cycle/timeline`,
    checkInWithManagerReview: `${API_URL}/api/check-in-with-manager`,
    previousGoalCycles: `${API_URL}/api/action-items/previous-three-cycles`,
    managerEmployeeList: `${API_URL}/api/employees/manager`,
    employeesByManager: `${API_URL}/api/employees/by-manager`,
    resendMail: `${API_URL}/api/resend-welcome-email`,
    userActivity: `${API_URL}/api/user-activity`,
    microsoftAuth: 'https://graph.microsoft.com/v1.0/me',
    zohoAuth: 'https://accounts.zoho.com/oauth/v2',
    organisation: `${API_URL}/api/organisation`,
    analytics: `${API_URL}/api/analytics`,
    slack: `${API_URL}/api/slack`,
    activeEmployees: `${API_URL}/api/get-all/by-review-cycle`,
    suggestionListAddEdit: `${API_URL}/api/suggestion`,
    suggestionTags: `${API_URL}/api/suggestion/progress-list`,
    suggestionPendingCount: `${API_URL}/api/suggestion/pending-count`,
    externalFeedback: `${API_URL}/api/feedback-request/external`,
    weightedScore: `${API_URL}/api/self-review/weighted-score`,
    previousGoalsActionItems: `${API_URL}/api/action-items/progress-list`,
    goalItemEdit: `${API_URL}/api/action-items` // pass /{id} at end
};

export default apiUrls;
